### ISSUE TITLE
Symlink parameters inverted

### ISSUE THREAD

**Issue by joknarf** [mysecureshell/mysecureshell#13]
It seems the symlink (ln) command takes inverted parameters
sftp> ln a b
should create a link b -> a
the link created is a -> b

FSSymlink(oldPath, newPath) should be FSSymlink(newPath, oldPath)

**Comment by Teka101** [comment]
Fixed issue in branche "issue13".

**Comment by pellcorp** [comment]
I don't actually think this was fixed in 2015, its still an issue
