### ISSUE TITLE
Connecting takes forever reading/opening directories for the user

### ISSUE THREAD

**Issue by llum** [mysecureshell/mysecureshell#22]
Some of my users are finding it hard for directories to be opened to them. When I check on the server, it says the user is connected. On the client it shows "Reading directory. 
Please help!

Users cannot connect with filezilla - any ideas why?

Thanks,
Elizabeth

**Comment by Teka101** [comment]
Can we have more informations:
* version of FileZilla
* version of MySecureShell
* OS and version

Thank you.

**Comment by deimosfr** [comment]
Hi, without answer from you, I'm closing the issue
