### ISSUE TITLE
User permission denied.

### ISSUE THREAD

**Issue by dwalls524** [mysecureshell/mysecureshell#23]
Installed MySecureShell everything working great.
Changed my users home path to a directory buried in /var/www/html.
Can read and download files without issue.
Cannot upload.

Also, is there a way to hide all files in that directory?

Thanks.

**Comment by Teka101** [comment]
Check your rights in "/var/www/html".

Two choices to hide items:
* hide items when user don't have right to "read" it: [doc](http://mysecureshell.readthedocs.org/en/latest/tags/childs/hidenoaccess.html)
* hide items for all users: [doc](http://mysecureshell.readthedocs.org/en/latest/tags/parents/filespec.html)
