### ISSUE TITLE
Can't connect with git

### ISSUE THREAD

**Issue by Techniv** [mysecureshell/mysecureshell#27]
Hi!

I used a preview version of mysecureshell to secure my git acces and it worked perfectly.

But after an upgrade to the 2.0 I can't connect when I use git over OpenSSH:

```
Shell access is disabled !fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

All work fine for SFTP.

Any idea ?

**Comment by Teka101** [comment]
Hi,

GIT need a shell access on SSH... so you have to authorize users to have shell with tag Shell.
