### ISSUE TITLE
sudo -s

### ISSUE THREAD

**Issue by TheSkyHeart** [mysecureshell/mysecureshell#28]
Hi,

I have installed and configure MySecureShell on ubuntu 12.04 server, everything works fine and i set the shell in sftp_config form one user to have /bin/bash, i can login with that user using ssh but when i issue the command sudo -s i get Shell access is disabled ! 
is there something that i'm missing?

**Comment by deimosfr** [comment]
Hi,

Sorry for the late answer. Could you please paste your configuration of MySecureShell and sudo please?

Thanks
