### ISSUE TITLE
Repository unavailable (Debian Wheezy / Raspbian)

### ISSUE THREAD

**Issue by Geabulek** [mysecureshell/mysecureshell#29]
Hi, 
I am following documentation and installation fails at 3.2.1.2. 

apt-get update gives
```
Réception de : 3 http://mysecureshell.free.fr testing/main Sources
Err http://mysecureshell.free.fr testing/main armhf Packages
  404  Not Found
Ign http://mysecureshell.free.fr testing/main Translation-fr_FR
Ign http://mysecureshell.free.fr testing/main Translation-fr
Ign http://mysecureshell.free.fr testing/main Translation-en
```

apt-get install mysecureshell gives
```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet mysecureshell
```

Raspbian version: https://www.raspberrypi.org/downloads/raspbian/

**Comment by Teka101** [comment]
MySecureShell repository only support i686 and amd64.

**Comment by deimosfr** [comment]
Hi,

If you're trying to use it on Debian, I can suggest Jessie which is compatible with other architecture. Please take a look here: https://packages.debian.org/jessie/mysecureshell

Hope this will help
