### ISSUE TITLE
Running netbeans from sftp

### ISSUE THREAD

**Issue by amadojss** [mysecureshell/mysecureshell#30]
First of all congratulations for this project and to apologize for my bad English.
I'm trying to run netbeans from a mounting sshfs. It allows me to install a mount point / opt. But try to run the program the initial screen appears and closes without an error. The server is a debian 8 and file /var/log/sftp-server.log  shows no error.

Is it possible to run programs from sftp?

Thank you.

**Comment by deimosfr** [comment]
Hi,

Sorry for the late answer. Have you tried to connect with a classic client (winscp, filezilla...) or simply tried to telnet the server to be sure you can connect from the workstation where netbeans runs ?
