### ISSUE TITLE
following #25: solaris compilation error

### ISSUE THREAD

**Issue by vercetty92** [mysecureshell/mysecureshell#31]
Hi Teka,

Since you have corrected issue #25, i didn't try to compile again mysecureshell on solaris as my "client" was silent, but he now needs me to try to install again a newer version than 1.22^^

So I have downloaded the source for 2.0 and tried to compil it, but I got another error.

2 questions : 
- I'm not very familiar with git, but I was expecting to see the file you have corrected in #25  (log.c) in the 2.0 source file, but not. I needed to download only the corrected file then replace the faulted file with this one. So you don't update the source with the new corrected file? (it's just for my info, again I'm not very familiar with git and user's habit^^)
- I also tried to download the 1.33 source, but it's empty (there is only a readme file), is it normal?

Thx a lot 

gmake all
Compile         [SftpServer/Log.c]
Compile         [SftpServer/Encoding.c]
SftpServer/Encoding.c: In function 'convertToUtf8':
SftpServer/Encoding.c:48:4: attention : passing argument 2 of 'libiconv' from incompatible pointer type [enabled by default]
/opt/csw/include/iconv.h:83:15: note: expected 'const char *_' but argument is of type 'char *_'
SftpServer/Encoding.c: In function 'convertFromUtf8':
SftpServer/Encoding.c:81:4: attention : passing argument 2 of 'libiconv' from incompatible pointer type [enabled by default]
/opt/csw/include/iconv.h:83:15: note: expected 'const char *_' but argument is of type 'char *_'
Compile         [SftpServer/Admin.c]
Compile         [SftpServer/SftpWho.c]
SftpServer/SftpWho.c: In function 'SftpWhoReleaseStruct':
SftpServer/SftpWho.c:168:3: attention : passing argument 1 of 'shmdt' from incompatible pointer type [enabled by default]
/usr/include/sys/shm.h:149:5: note: expected 'char _' but argument is of type 'struct t_sftpglobal *'
Compile         [SftpServer/SftpExt.c]
Compile         [SftpServer/SftpServer.c]
Compile         [SftpServer/GetUsersInfos.c]
Compile         [SftpServer/Stats.c]
Compile         [SftpServer/Access.c]
Compile         [SftpServer/FileSystem.c]
Compile         [SftpServer/FileSystemAcl.c]
SftpServer/FileSystemAcl.c: In function 'FSEnumAcl':
SftpServer/FileSystemAcl.c:38:8: erreur: storage size of 'acl' isn't known
SftpServer/FileSystemAcl.c:49:3: attention : implicit declaration of function 'acl_get_file' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:49:38: erreur: 'ACL_TYPE_ACCESS' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:49:38: note: each undeclared identifier is reported only once for each function it appears in
SftpServer/FileSystemAcl.c:58:3: erreur: unknown type name 'acl_entry_t'
SftpServer/FileSystemAcl.c:60:3: attention : implicit declaration of function 'acl_get_entry' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:60:26: erreur: 'ACL_FIRST_ENTRY' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:64:5: erreur: unknown type name 'acl_permset_t'
SftpServer/FileSystemAcl.c:65:5: erreur: unknown type name 'acl_tag_t'
SftpServer/FileSystemAcl.c:69:5: attention : implicit declaration of function 'acl_get_tag_type' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:69:5: attention : implicit declaration of function 'acl_get_permset' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:71:17: erreur: 'ACL_MASK' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:78:6: attention : implicit declaration of function 'acl_get_perm' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:78:36: erreur: 'ACL_READ' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:79:31: erreur: 'ACL_WRITE' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:80:31: erreur: 'ACL_EXECUTE' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:84:11: erreur: 'ACL_USER' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:85:7: attention : implicit declaration of function 'acl_get_qualifier' [-Wimplicit-function-declaration]
SftpServer/FileSystemAcl.c:89:8: attention : passing argument 1 of 'acl_free' from incompatible pointer type [enabled by default]
/usr/include/sys/acl.h:200:13: note: expected 'struct acl_t *' but argument is of type 'int *'
SftpServer/FileSystemAcl.c:93:11: erreur: 'ACL_GROUP' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:98:8: attention : passing argument 1 of 'acl_free' from incompatible pointer type [enabled by default]
/usr/include/sys/acl.h:200:13: note: expected 'struct acl_t *' but argument is of type 'int *'
SftpServer/FileSystemAcl.c:102:11: erreur: 'ACL_USER_OBJ' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:106:11: erreur: 'ACL_GROUP_OBJ' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:110:11: erreur: 'ACL_OTHER' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:117:30: erreur: 'ACL_NEXT_ENTRY' undeclared (first use in this function)
SftpServer/FileSystemAcl.c:38:8: attention : unused variable 'acl' [-Wunused-variable]
gmake: *_\* [SftpServer/FileSystemAcl.o] Error 1

**Comment by Teka101** [comment]
Hi,

I think it's more a dependency problems... can you send the output of "./configure" script ?

Thanks.

**Comment by vercetty92** [comment]
Hi, sure:

./configure 
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for sed... /usr/bin/sed
checking for sudo... /opt/csw/bin/sudo
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/sfw/bin/ggrep
checking for egrep... /usr/sfw/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether gcc needs -traditional... no
checking whether ln -s works... yes
checking for inline... inline
checking for an ANSI C-conforming const... yes
checking for uid_t in sys/types.h... yes
checking for int32_t... yes
checking for mode_t... yes
checking for off_t... yes
checking for ssize_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking return type of signal handlers... void
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for u_int8_t... no
checking for u_int16_t... no
checking for u_int32_t... no
checking for u_int64_t... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for unistd.h... (cached) yes
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking for sys/param.h... (cached) yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/socket usability... no
checking sys/socket presence... no
checking for sys/socket... no
checking for netinet/in.h... (cached) yes
checking sys/acl.h usability... yes
checking sys/acl.h presence... yes
checking for sys/acl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for sys/mount.h... yes
checking whether closedir returns void... no
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking whether stat accepts an empty string... no
checking whether lstat accepts an empty string... no
checking for unistd.h... (cached) yes
checking for working chown... yes
checking type of array argument to getgroups... gid_t
checking for size_t... yes
checking for getgroups... yes
checking for working getgroups... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for strftime... yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for alarm... yes
checking for working mktime... no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for sys/socket.h... (cached) yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking whether stat file-mode macros are broken... no
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether time.h and sys/time.h may both be included... (cached) yes
checking for endgrent... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for statfs... yes
checking for statvfs... yes
checking for getgroups... (cached) yes
checking for strlcpy... yes
checking for strlcat... yes
checking for acl... yes
checking for acl_get_perm_np... no
checking for atexit... yes
checking for dup2... yes
checking for endpwent... yes
checking for gettimeofday... yes
checking for memset... yes
checking for mkdir... yes
checking for realpath... yes
checking for regcomp... yes
checking for rmdir... yes
checking for select... yes
checking for setenv... yes
checking for memmove... yes
checking for openlog... yes
checking for syslog... yes
checking for closelog... yes
checking for vsyslog... yes
checking for connect... no
checking for gethostbyaddr in -lnsl... yes
checking for gethostbyaddr... yes
checking for gethostbyname... yes
checking for inet_ntoa... yes
checking for iconv_open... yes
checking for iconv_close... yes
checking for iconv... yes
checking for acl_get_entry in -lacl... no
checking for gnutls_hash_init in -lgnutls... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating install.sh
config.status: creating uninstaller.sh
config.status: creating utils/sftp-user
config.status: creating utils/sftp-verif
config.status: creating config.h
config.status: config.h is unchanged
checking for a BSD-compatible install... /opt/csw/bin/ginstall -c

MySecureShell has been configured with the following options:
          Log file: /var/log/sftp-server.log (color: no)
     User binaries: /usr/bin
     Shutdown file: /etc/sftp.shut
Configuration file: /etc/ssh/sftp_config
 Compilation flags: 

Option supported:
ACL               : yes
Remote Admin      : yes
UTF-8 Encoding    : yes

Sftp extension supported:
Disk Usage        : yes
Disk Usage OpenSSH: yes
File Hashing      : no

**Comment by Teka101** [comment]
Hum ACL is detected but not installed... i should fix it...

Before you can edit "config.h" and remove all lines contains "ACL" and it should compile after this modification.

**Comment by vercetty92** [comment]
HI,

I have removed all the lines with "acl", it concerns these lines:

/* Define to 1 if you have the `acl' function. */
#define HAVE_ACL 1
/* Define to 1 if you have the `acl_get_perm_np' function. */
/* #undef HAVE_ACL_GET_PERM_NP */
/* Define to 1 if you have the <cygwin/acl.h> header file. */
/* #undef HAVE_CYGWIN_ACL_H */
/* Define to 1 if you have the `acl' library (-lacl). */
/* #undef HAVE_LIBACL */
/* Define to 1 if you have the <sys/acl.h> header file. */
#define HAVE_SYS_ACL_H 1
/* ACL */
#define MSS_ACL 1


Here is the gmake all result aftert I removed all the line that contains "acl" in config.h:

thx

gmake all 
Compile         [Core/main.c]
Compile         [Core/string.c]
Compile         [Core/parsing.c]
Compile         [Core/hash.c]
Compile         [Core/conf.c]
Compile         [Core/convert.c]
Compile         [Core/user.c]
Compile         [Core/prog.c]
Compile         [Core/ip.c]
Compile         [Core/FileSpec.c]
Compile         [SftpServer/Buffer.c]
Compile         [SftpServer/Encode.c]
SftpServer/Encode.c:222:13: attention : 'EncodeACLCallBack' defined but not used [-Wunused-function]
SftpServer/Encode.c:276:13: attention : 'EncodeACL' defined but not used [-Wunused-function]
Compile         [SftpServer/Handle.c]
Compile         [SftpServer/Send.c]
Compile         [SftpServer/Sftp.c]
Compile         [SftpServer/Util.c]
Compile         [SftpServer/Log.c]
SftpServer/Log.c:4:1: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:7:19: attention : constante caract�re trop longue pour son type [enabled by default]
SftpServer/Log.c:13:5: erreur: stray '\302' in program
SftpServer/Log.c:13:5: erreur: stray '\267' in program
SftpServer/Log.c:13:5: erreur: stray '\302' in program
SftpServer/Log.c:13:5: erreur: stray '\267' in program
SftpServer/Log.c:56:32: attention : caract�re ' de terminaison manquant [enabled by default]
SftpServer/Log.c:56:7: erreur: caract�re ' de terminaison manquant
SftpServer/Log.c:102:32: attention : caract�re ' de terminaison manquant [enabled by default]
SftpServer/Log.c:102:7: erreur: caract�re ' de terminaison manquant
SftpServer/Log.c:292:28: attention : constante caract�re trop longue pour son type [enabled by default]
SftpServer/Log.c:292:752: attention : la d�finition de donn�es n'a pas de type ni de classe de stockage [enabled by default]
SftpServer/Log.c:292:752: attention : type defaults to 'int' in declaration of 'protocol_type' [-Wimplicit-int]
SftpServer/Log.c:292:766: erreur: 'clone' undeclared here (not in a function)
SftpServer/Log.c:292:771: erreur: expected ',' or ';' before string constant
SftpServer/Log.c:292:834: erreur: suffixe � b18ac6bfccdb6863dc008a792749 � invalide pour une constante flottante
SftpServer/Log.c:292:937: erreur: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
SftpServer/Log.c:292:947: erreur: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
SftpServer/Log.c:292:947: erreur: stray '#' in program
SftpServer/Log.c:292:1004: erreur: expected identifier or '(' before string constant
SftpServer/Log.c:292:1242: attention : caract�re " de terminaison manquant [enabled by default]
SftpServer/Log.c:292:1004: erreur: caract�re " de terminaison manquant
SftpServer/Log.c:314:46: erreur: suffixe � b58c737522a7e4618a06ad5780f5 � invalide pour une constante enti�re
SftpServer/Log.c:531:11: erreur: suffixe � def98 � invalide pour une constante enti�re
SftpServer/Log.c:538:11: erreur: stray '#' in program
SftpServer/Log.c:678:9: erreur: stray '#' in program
SftpServer/Log.c:678:151: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:678:196: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:682:9: erreur: stray '#' in program
SftpServer/Log.c:682:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:682:188: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:686:9: erreur: stray '#' in program
SftpServer/Log.c:686:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:686:188: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:690:9: erreur: stray '#' in program
SftpServer/Log.c:690:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:690:189: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:694:9: erreur: stray '#' in program
SftpServer/Log.c:694:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:694:188: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:698:9: erreur: stray '#' in program
SftpServer/Log.c:698:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:698:187: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:702:9: erreur: stray '#' in program
SftpServer/Log.c:702:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:702:189: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:706:9: erreur: stray '#' in program
SftpServer/Log.c:706:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:706:189: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:710:9: erreur: stray '#' in program
SftpServer/Log.c:710:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:710:189: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:714:9: erreur: stray '#' in program
SftpServer/Log.c:718:9: erreur: stray '#' in program
SftpServer/Log.c:718:149: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:718:189: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:722:9: erreur: stray '#' in program
SftpServer/Log.c:726:9: erreur: stray '#' in program
SftpServer/Log.c:726:151: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:726:190: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:730:9: erreur: stray '#' in program
SftpServer/Log.c:730:151: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:730:203: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:739:9: erreur: stray '#' in program
SftpServer/Log.c:743:9: erreur: stray '#' in program
SftpServer/Log.c:747:9: erreur: stray '#' in program
SftpServer/Log.c:751:9: erreur: stray '#' in program
SftpServer/Log.c:755:9: erreur: stray '#' in program
SftpServer/Log.c:792:9: erreur: stray '#' in program
SftpServer/Log.c:800:9: erreur: stray '#' in program
SftpServer/Log.c:804:72: attention : la d�finition de donn�es n'a pas de type ni de classe de stockage [enabled by default]
SftpServer/Log.c:804:72: attention : type defaults to 'int' in declaration of 't_log' [-Wimplicit-int]
SftpServer/Log.c:804:78: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:813:186: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:883:9: erreur: stray '#' in program
SftpServer/Log.c:907:9: erreur: stray '#' in program
SftpServer/Log.c:961:9: erreur: stray '#' in program
SftpServer/Log.c:961:9: erreur: stray '#' in program
SftpServer/Log.c:1009:9: erreur: stray '#' in program
SftpServer/Log.c:1110:9: erreur: stray '#' in program
SftpServer/Log.c:1118:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1143:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1168:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1197:9: erreur: stray '#' in program
SftpServer/Log.c:1209:9: erreur: stray '#' in program
SftpServer/Log.c:1233:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1393:9: erreur: stray '\' in program
SftpServer/Log.c:1409:9: erreur: stray '#' in program
SftpServer/Log.c:1413:9: erreur: stray '\' in program
SftpServer/Log.c:1425:9: erreur: stray '#' in program
SftpServer/Log.c:1437:9: erreur: stray '\' in program
SftpServer/Log.c:1437:9: erreur: stray '\' in program
SftpServer/Log.c:1437:649: erreur: suffixe � m � invalide pour une constante enti�re
SftpServer/Log.c:1437:9: erreur: stray '\' in program
SftpServer/Log.c:1449:9: erreur: stray '#' in program
SftpServer/Log.c:1485:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1506:72: erreur: expected identifier or '(' before '<' token
SftpServer/Log.c:1516:28: attention : caract�re ' de terminaison manquant [enabled by default]
SftpServer/Log.c:1516:3: erreur: caract�re ' de terminaison manquant
SftpServer/Log.c:1547:18: erreur: expected identifier or '(' before numeric constant
gmake: *** [SftpServer/Log.o] Error 1

**Comment by Teka101** [comment]
Hum very strange...

I need to see it more in details :)
