### ISSUE TITLE
2015-10-20 10:12:58 [24504][u01]Server 'x.x.x.x' reached maximum connexion (128 clients)

### ISSUE THREAD

**Issue by iCoding2014** [mysecureshell/mysecureshell#32]
## zhyh MySecureShell Configuration File ##
# Default rules for everybody

<Default>
        GlobalDownload          300m    #total speed download for all clients
        GlobalUpload            300m    #total speed download for all clients (0 for unlimited)
        Download                20k    #limit speed download for each connection
        Upload                  20k    #unlimit speed upload for each connection
        StayAtHome              true    #limit client to his home
        VirtualChroot           true    #fake a chroot to the home account
        LimitConnection         1024    #max connection for the server sftp
        LimitConnectionByUser   300     #max connection for the account
        LimitConnectionByIP     300     #max connection by ip for the account
        Home                    /home/sftp     #overrite home of the user but if you want you can use
        IdleTimeOut             5m      #(in second) deconnect client is idle too long time
        HideNoAccess            true    #Hide file/directory which user has no access
        DefaultRights           0644 0755       #Set default rights for new file and new directory
        ShowLinksAsLinks        false   #show links as their destinations
        ConnectionMaxLife       1d      #limits connection lifetime to 1 day
        Charset                 "UTF8"
        CreateHome              true
        LogFile                 /tmp/sftp-server.log
        DisableAccount          false
</Default>

**Comment by Teka101** [comment]
Hi,

Max clients is limited to 128 connections (hard coded).
So it's not a bug, it's a limitation of current version of MySecureShell.

**Comment by iCoding2014** [comment]
My English is not good, but I try to say it.
If you logged in over 128 using u01 ,At this point will exceed the limit. and i kill all mysecureshell process. After I finished, I use another user mysecureshell login u02, login is not successful, or throws an error.
2015-10-21 00:12:09 [22467][u02]Server '192.168.0.179' reached maximum connexion (128 clients)
Other user u03, u04 is also the same problem.

**Comment by iCoding2014** [comment]
Hi,
i remove all shared memory owned by u01, other users u02 u03 can login successful .

**Comment by marlemion** [comment]
Hi. I ran into the same problem. Only one user can login into my server anymore. Why is there any regulation anyway? How can I reset the users? It is quite annoying. :(

**Comment by marlemion** [comment]
Btw. I added a new user and even this user was not allowed anymore to login.

**Comment by swarajban** [comment]
@marlemion thank you! I was running into same problem and fixed it by running:

```
$ chmod 4755 /usr/bin/mysecureshell
$ service ssh restart
```

Pretty crazy bug / limitation

**Comment by vinoth-kumar-r** [comment]
How can I increase the maximum connections from 128?

**Comment by Teka101** [comment]
Hi @vinoth-kumar-r,

Download source from github and edit file `SftpServer/SftpWho.h` , the line with `SFTPWHO_MAXCLIENT` set the maximum of users.
Then compile and install MySecureShell
