### ISSUE TITLE
MySecureShell is version 2.0 ignores /etc/passwd home for user

### ISSUE THREAD

**Issue by davidfavor** [mysecureshell/mysecureshell#33]
MySecureShell forces home directory to /home/$user rather than correctly using /etc/passwd entry for extracting home directory.

**Comment by deimosfr** [comment]
Hi,

Can you please paste your conf. Are you sure your user got MySecureShell as the current shell ?

Thanks

**Comment by davidfavor** [comment]
:::: Summary

Thanks for your quick response.

I'm also happy to build + install from git, if this challenge is resolved in latest code.

Seems like having StayAtHome + VirtualChroot both set should chroot user to their /etc/passwd home directory.

Maybe what's required is to comment out the "Home /home/$USER" stanza, which appears in the default config file. Maybe this is an Ubuntu-ism which breaks /etc/passwd home dir setting.

:::: Version of code running, from Ubuntu repository
net4-dev# mysecureshell --version
MySecureShell is version 2.0 build on Nov 19 2014

Options:
  ACL support: yes
  UTF-8 support: yes

Sftp Extensions:
  Disk Usage
  Disk Usage (OpenSSH)
  File Hashing

net4-dev# grep rmt /etc/passwd
monitor-rmtcenter:x:1000:1001:Funnel Insurance Monitor:/etc/funnel-insurance/monitors/rmtcenter:/usr/bin/mysecureshell

:::: System Info

net4-dev# uname -a
Linux net4.bizcooker.com 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

net4-dev# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

:::: Install Commands Issued

sudo bash
apt-get install mysecureshell
mkdir -p /etc/funnel-insurance/monitors/rmtcenter
grep -q monitor-rmtcenter /etc/passwd || useradd --comment 'Funnel Insurance Monitor' --create-home --home /etc/funnel-insurance/monitors/rmtcenter -s /usr/bin/mysecureshell monitor-rmtcenter

:::: User Info After Login

sfnet4-dev# sftp-who 
--- 1 / 10 clients ---
Global used bandwidth : 0 bytes/s / 0 bytes/s
PID: 7562   Name: monitor-rmtcenter   IP: cpe-173-174-45-207.austin.res.rr.com
	Home: /home/monitor-rmtcenter
	Status: idle    Path: 
	File: 
	Connected: 2015/11/19 05:15:45 [since 06s]
	Speed: Download: 0 bytes/s [5.00 kbytes/s]  Upload: 0 bytes/s [unlimited]
	Total: Download: 134 bytes   Upload: 23 bytes

:::: Config File

Default config file used. No changes made.

net4-dev# cat /etc/ssh/sftp_config 
## MySecureShell Configuration File ##
# To get more informations on all possible options, please look at the doc:
# http://mysecureshell.readthedocs.org

#Default rules for everybody
<Default>
	GlobalDownload		50k	#total speed download for all clients
					# o -> bytes   k -> kilo bytes   m -> mega bytes
	GlobalUpload		0	#total speed download for all clients (0 for unlimited)
	Download 		5k	#limit speed download for each connection
	Upload 			0	#unlimit speed upload for each connection
	StayAtHome		true	#limit client to his home
	VirtualChroot		true	#fake a chroot to the home account
	LimitConnection		10	#max connection for the server sftp
	LimitConnectionByUser	1	#max connection for the account
	LimitConnectionByIP	2	#max connection by ip for the account
	Home			/home/$USER	#overrite home of the user but if you want you can use
						#	environment variable (ie: Home /home/$USER)
	IdleTimeOut		5m	#(in second) deconnect client is idle too long time
	ResolveIP		true	#resolve ip to dns
#	IgnoreHidden		true	#treat all hidden files as if they don't exist
#	DirFakeUser		true	#Hide real file/directory owner (just change displayed permissions)
#	DirFakeGroup		true	#Hide real file/directory group (just change displayed permissions)
#	DirFakeMode		0400	#Hide real file/directory rights (just change displayed permissions)
					#Add execution right for directory if read right is set
	HideNoAccess		true	#Hide file/directory which user has no access
#	MaxOpenFilesForUser	20	#limit user to open x files on same time
#	MaxWriteFilesForUser	10	#limit user to x upload on same time
#	MaxReadFilesForUser	10	#limit user to x download on same time
	DefaultRights		0640 0750	#Set default rights for new file and new directory
#	MinimumRights		0400 0700	#Set minimum rights for files and dirs

	ShowLinksAsLinks	false	#show links as their destinations
#	ConnectionMaxLife	1d	#limits connection lifetime to 1 day

#	Charset			"ISO-8859-15"	#set charset of computer
</Default>

#Rules only for group ftp
#<Group ftp>
#	Download	25 k/s
#	LogFile		/var/log/sftp-server_ftp.log	#Change logfile
#	ExpireDate	"2007-02-28 18:31:01"
#</Group>

#<Group sftp_administrator>
#	IsAdmin		true		#can admin the server
#	VirtualChroot	false		#you must disable chroot to have a full support of admin
#	StayAtHome	true
#	IdleTimeOut	0
#</Group>

#<Group old_client>
#	SftpProtocol		3	#force protocol SFTP
#	DisableAccount		true	#disable account
#</Group>

#Rules only for group ftpnolimit
#<Group ftpnolimit>
#	Download		0	#0 = unlimited
#	IdleTimeOut		0	#no timeout
#	DirFakeUser		false	#show real user on file/directory
#	DirFakeGroup		false	#show real group on file/directory
#	DirFakeMode		0	#show real rights on file/directory
#	MaxReadFilesForUser	0	#0 = unlimited but still have the restriction MaxOpenFilesForUser
#</Group>

#<IpRange 192.168.0.1-192.168.0.5>
#	ByPassGlobalDownload	true	#bypass GlobalDownload restriction
#	ByPassGlobalUpload	true	#bypass GlobalUpload restriction
#	Download		0
#	DisableAccount		false	#enable account
#	IdleTimeOut		0	#disable timeout
#	LimitConnectionByIP	0	#no limit
#</IpRange>

#<Group trusted_users>
#	Shell		/bin/tcsh	#give a shell access to TRUSTED clients !!!
#</Group>

#<VirtualHost *:22> 
#	DirFakeUser	false	#show real user on file/directory
#	DirFakeGroup	false	#show real group on file/directory
#	DirFakeMode	0	#show real rights on file/directory
#	HideNoAccess	false
#	IgnoreHidden	false
#</VirtualHost>

#Include /etc/my_sftp_config_file	#include this valid configuration file

**Comment by deimosfr** [comment]
Hi,

You're right, try to comment the Home parmeter. This forces the home directory to be override by the one in the configuration file.

**Comment by davidfavor** [comment]
Ah... So this is an Ubuntu-ism...

Working perfect, with home commented out.

Thanks for your fast reply!
