### ISSUE TITLE
install on ubuntu 14.04

### ISSUE THREAD

**Issue by cphubs** [mysecureshell/mysecureshell#34]
Hi 
How can install mysecureshell on ubuntu14.04 
i run 
apt-key adv --keyserver pool.sks-keyservers.net --recv-keys E328F22B
but this error eccured:

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.OZ6uSPRVwm --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver pool.sks-keyservers.net --recv-keys E328F22B
gpg: requesting key E328F22B from hkp server pool.sks-keyservers.net
?: pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by bellera** [comment]
git clone https://github.com/mysecureshell/mysecureshell
cd mysecureshell
./configure --with-logcolor=yes
make all
make install
cd /bin
ln -s /usr/bin/mysecureshell MySecureShell

Edit /etc/ssh/sftp_config

&

service ssh restart

**Comment by bellera** [comment]
Oops!

Don't forget:

chmod 4755 /usr/bin/mysecureshell

The command sftp-verif can help to test your installation:

http://mysecureshell.readthedocs.org/en/latest/usages_admin.html#check-mysecureshell-installation

**Comment by cphubs** [comment]
./configure --with-logcolor=yes

configure: error: in `/root/mysecureshell':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

make all
make: *** No rule to make target `all'.  Stop.

**Comment by bellera** [comment]
@cphubs,

Are you doing this as superuser ?

Do you have your 14.04 LTS up-to-date?

Do you have gcc installed?

# ./configure --with-logcolor=yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out

**Comment by cphubs** [comment]
I solve it
I use Vultr VPS and must be install
apt-get update && apt-get install -y build-essential

Thanks

**Comment by deimosfr** [comment]
Hi,

MySecureShell is now available by default in Ubuntu. Nice to see that you could install it.

Sorry for the delay
