### ISSUE TITLE
Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by oviliz** [mysecureshell/mysecureshell#36]
How do I install this on Ubuntu 14?

The documentation is covering only Ubuntu 12 and 10 and these doesn't looks as available anymore:

```deb http://mysecureshell.free.fr/repository/index.php/ubuntu testing main
deb-src http://mysecureshell.free.fr/repository/index.php/ubuntu testing main```

**Comment by Teka101** [comment]
Old package are still available on private repository (mysecureshell.free.fr).
But if you have Ubuntu 15 (or superior) you can use official repository of Ubuntu :)

**Comment by bellera** [comment]
git clone https://github.com/mysecureshell/mysecureshell
cd mysecureshell
./configure --with-logcolor=yes
make all
make install
cd /bin
ln -s /usr/bin/mysecureshell MySecureShell

Edit /etc/ssh/sftp_config

&

service ssh restart

**Comment by bellera** [comment]
Oops!

Don't forget:

chmod 4755 /usr/bin/mysecureshell

The command sftp-verif can help to test your installation:

http://mysecureshell.readthedocs.org/en/latest/usages_admin.html#check-mysecureshell-installation

**Comment by oviliz** [comment]
Thank you @bellera. I have managed to install it from source by the end even I didn't want too as I love instaling from repository from an "keeping updated" perspective.
The next time, if still would not be part of the next LTS, Ubuntu 16.04, I will try your suggestion.
