### ISSUE TITLE
Different access in subfolders

### ISSUE THREAD

**Issue by forestmountain** [mysecureshell/mysecureshell#38]
I already have a functioning SFTP server with both a default and various group definitions.
Now I have a need for a special folder (topfolder) where a group of admins have download and upload rights to any thing below (the subfolders).

In the folder partner1 the user partner1 has only download rights (no upload or change rights)
In the folder partner2 the user partner2 has only download rights (no upload or change rights)
and so on. User partnerX can only access partnerX folder.

**- (topfolder)** < group of admin users has r/w rights
    **- subfolder partner1** < user partner1 has read rights
    **- subfolder partner2** < user partner2 has read rights
    **- subfolder partner3** < user partner3 has read rights
    **- subfolder partnerN** < user partnerN has read rights

Can this be achieved easily with MySecureShell and how?

/Kent

**Comment by forestmountain** [comment]
Anyone?

**Comment by Gijom** [comment]
Hi,

I think what you ask is not related to the SFTP server itself. It is more related to the rights you assign on your filesystem.

What you ask for could be achieved in at least two ways:
- making use of groups (i.e. the group admin would have access to all subfolders, and then each folder is given to a single user with only read access);
- making use of ACLs to enforce separate rights for different users (see. http://bencane.com/2012/05/27/acl-using-access-control-lists-on-linux/)

**Comment by forestmountain** [comment]
Thanks. I did get this working with ACLs. Works as intented.

Actually my point of asking was that I thought this kind of scenarios should or could be configured better with the use of group definitions in the mysecureshell's config (so as to having all SFTP user configuration in one place). The mysecureshell documentation mentions something of being able to make use of ACLs but doesn't describe how).

Consider case closed.

**Comment by Gijom** [comment]
I believe that "being able to make use of ACLs" simply means that it can take into account ACLs permissions attributed on the filesystem. But I might be wrong...
