### ISSUE TITLE
sftp-who returns 0 clients despite of the presence of one

### ISSUE THREAD

**Issue by Gijom** [mysecureshell/mysecureshell#39]
Hello,

although some user(s) are connected sftp-who always returns that 0 connexion are active.

For instance I connect a user "test", the list of processes contains:
`test     27549 27548  0 12:39 ?        00:00:00 MySecureShell -c /usr/libexec/openssh/sftp-server`
the user can access files and end-up in the MySecureShell configured root directory (different from the sshd one).
However `sftp-who` returns:
`--- 0 / 10 clients ---`

and `sftp-user list` returns:
`test`

Having a look at the code I noticed that user information was taken from an IPC shared memory. I do not know about IPC shared memories but POSIX ones are generally located in /dev/shm. I could not see any shm corresponding to MySecureShell in that folder.

Some more info:
```
$ uname -a
Linux my@host.fr 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhast-release
CentOS release 6.7 (Final)

$ MySecureShell --version
MySecureShell is version 1.33 build on Mar 26 2014

Options:
  ACL support: yes
  UTF-8 support: yes

Sftp Extensions:
  Disk Usage
  Disk Usage (OpenSSH)
  File Hashing
```

**Comment by Gijom** [comment]
Actually I realized that it works if I have elevated rights (root). Is it a feature or a bug ?

**Comment by deimosfr** [comment]
Hi,

Sorry for the late answer, it's not a bug. Elevated permissions are required.
