### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by fanfoni** [mysecureshell/mysecureshell#41]
Hi,

Any chance to support CentOS 7?

**Comment by Teka101** [comment]
MySecureShell should already work for CentOS 7 :)

**Comment by fanfoni** [comment]
I've followed [this guide](http://www.servermom.org/configure-mysecureshell-ftp-server/2450/) and could not make the daemon work.

Its working after read the the mysecureshell doesn't need that daemon.

Thanks =)

**Comment by Teka101** [comment]
No problem :+1:
