### ISSUE TITLE
Request for LogFile documentation example

### ISSUE THREAD

**Issue by davidfavor** [mysecureshell/mysecureshell#42]
Setting default of...

LogFile         /var/log/mysecureshell.log

Only seems to work via...

1) touch /var/log/mysecureshell.log

2) chmod 777 /var/log/mysecureshell.log

Likely the solution to this is have the log file owned by group ftp + writeable by group ftp + all MySecureShell users be part of ftp group.

Be great if there was a write up about exactly what's required to setup log file correctly.

Thanks.

**Comment by davidfavor** [comment]
Maybe this exists in docs + I just missed it.

If docs already cover this, point me to the URL, as I seem to be missing it.

Thanks.

BTW, MySecureShell... to me... is the way sftp should work. MySecureShell has made my life very simple.

Thanks for the great code!

**Comment by Teka101** [comment]
Hello,

I think there is a problem in your MySecureShell installation.

Can you execute "sftp-verif" as "root" ?

**Comment by davidfavor** [comment]
Teka101 wrote:
> Hello,
> 
> I think there is a problem in your MySecureShell installation.
> 
> Can you execute "sftp-verif" as "root" ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <http://links.davidfavor.com/wf/click?upn=npdP0-2FMHcGNgMeleDP-2B5C62XU4tO5vM6CpcxEN-2FcdnHnHyR6vY6gnrpHyGKGnqjUgBA8gZO2ODU-2F7D-2F04999xj6xDy6rnAyBTFXkkny6Q0X0iSRb6cBti5SjemsM-2BQXd_s5UH8bhnBaopYjthcNSRcaP1Rp2h5cOSIRhM9iKKHNaQaMHaezSzzjQkf5g-2FCLhBd2Pyc6ZfuZaFX0YiSmmtyOyiTpbeuXkzs3ex-2B3XF9A3ol8Dr1hSDOylvBCQ9aGmWGuAuNxJZ9d5OPtTuCJqyuGbaUgXg05wOo3hY5lzgM9ssPQkYDwFqNMh-2BRu-2FYTMNFnh7AS34ZXDFrJsD2veRoZRBDMmg3JbYviZiDa5J0OxGZ1-2FPdwBgiFCYzOS6mDyminPB60ELB63MI2gJJ85zIYAR5TaR2kCkliODG4A6uv-2BNLbxi7zzqBj-2BBCsqcjvwgaTLvI-2FFtOeHd1ChuXCTKf4Q-3D-3D>
> 

Ah...

I did get the 755 -> 4755 fix question, so likely this was problem.

Thanks.

**Comment by Teka101** [comment]
Great news :+1:
