### ISSUE TITLE
no package for ubuntu 16.04

### ISSUE THREAD

**Issue by vince06fr** [mysecureshell/mysecureshell#43]
the last packages for ubuntu was for 12.04
16.04 is a LTS so can you provide an official package??
compiling is not a problem but upgrade just with a apt-get update && apt-get upgrade will be a better option than check the upgrade on github

**Comment by vince06fr** [comment]
I just see that mysecureshell is already packaged in the official ubuntu repository..
sorry for this post

**Comment by Teka101** [comment]
:+1:
