### ISSUE TITLE
custom config file to enable chrooted sftp in userspace

### ISSUE THREAD

**Issue by mateidavid** [mysecureshell/mysecureshell#45]
**Summary**. I'm trying to use MySecureShell to address a specific use case described below. I believe that addressing it requires adding the option to specify a custom config file on the command line. I am unsure how this fits in with the fact that sometimes MySecureShell uses suid 0. Modulo the last part, I'm offerring to write a PR about this issue.

**Details**. As you may know, the `~/.ssh/authorized_keys` file in OpenSSH allows one to specify a command associated with a specific key. I would like to use this mechanism to start a chrooted SFTP server, all in userspace, and in particular, without editing any files under `/etc/ssh`. The best I could do with OpenSSH is:

```
command="/usr/lib/openssh/sftp-server -d /path/to/chroot" ssh_rsa ...
```

The problem is that the SFTP server started this way is not chrooted, so one can do `cd ..`. Furthermore, the alternate `internal-sftp` server that comes with OpenSSH requires editing root config files.

While looking for a solution, I found MySecureShell, and I was excited by its `VirtualChroot` option. However, even with this option present, the solution to my use case is awkward, primarily because MySecureShell does not provide a mechanism to specify a custom config file on the command line. Without this, the options seem to be:
- Install MySecureShell as root, then edit `/etc/ssh/sftp_config`. But editing root files is what I'm trying to avoid. Also, this is restricted to systems where I have root access.
- Compile MySecureShell from source with a custom `--with-conffile`, put the executable in a custom location, then use that executable in `authorized_keys`. This is possible but awkward because, e.g., to use 2 different restricted keys, one has to use 2 copies of MySecureShell.

With all this in mind, I wanted to ask whether you would be open to the idea to add a command line option to MySecureShell, say `--config <file>`, which would direct it to use that custom configuration file instead of `/etc/ssh/sftp_config`. With something like this in place, my use case would be addressed by, e.g.:

```
command="/path/to/mysecureshell --config /path/to/custom/config -c sftp-server" ssh_rsa ...
```

I looked at the source code and it seems pretty straightforward to add it to `parse_args` in `Core/main.c`, so I could do it in a PR if you consider it would be useful.

My only concern is that I believe MySecureShell is sometimes installed with suid 0, and I assume that if one were allowed to change the config file, one should forfeit root priviledges for doing so. I'm not sure how to do this part, is there an easy way?

Thanks!

**Comment by Teka101** [comment]
Merge request is ready
