### ISSUE TITLE
OpenSuse Leap 42.1 problem

### ISSUE THREAD

**Issue by psposito** [mysecureshell/mysecureshell#46]
On openSUSE Leap 42.1 compiled and installed from source, ver. 1.33: 

When executing on terminal sftp msshftp@192.168.1.102, I get the message "port 22: No route to host Couldn't read packet: Connection reset by peer"
Please note that mysecureshell service is also missing from systemd services list.

**Comment by Teka101** [comment]
Hi,

OpenSSH is installed and service is up ?

**Comment by psposito** [comment]
Yes,

Installed, allowed (trusted) by firewalld and started...
