### ISSUE TITLE
Received unexpected end-of-file from SFTP server

### ISSUE THREAD

**Issue by zerotole** [mysecureshell/mysecureshell#49]
I am having an issue with ysecureshell and filezilla.  WinSCP works great.  With filezilla I can connect but then when I try and upload a file it gives error.

Error:	Received unexpected end-of-file from SFTP server
Error:	Could not connect to server

Then if I try and login again it states the same thing until i restart mysecureshell and then it will connect again.  

It is like it is only working with SCP??  

Any ideas?

**Comment by peylight** [comment]
I try to connect OpenWRT by Filezilla and i have the same problem!
Limit connections not working and other people have the same problem:
https://forum.openwrt.org/viewtopic.php?pid=279243#p279243
Any other solutions?

**Comment by swarajban** [comment]
@hussambuttalayacare thank you so much! That fixed my issue

**Comment by moxley** [comment]
The `LimitConnectionByUser` change fixed it for me to. Here's more context, for those who aren't familiar with administering mysecureshell.

The file you want to edit is `/etc/ssh/sftp_config`. In it, setting `LimitConnectionByUser` to `2` worked for me. There's nothing to restart, as mysecureconfig reloads the configuration on each user connection. Thanks.

**Comment by kb6671** [comment]
Any solution for `dropbear` ssh server with same error ?

**Comment by Teka101** [comment]
Hi @kb6671 , do you have change anything in `dropbear` configuration ?

**Comment by NAICOLAS** [comment]
> ## Any solution for `dropbear` ssh server with same error ?
> update 2019-11-14 Thanks @Teka101 my problem [solved](https://serverfault.com/a/990194) , it's occur because of package `openssh-sftp-server` missing

Installing openssh-sftp-server solved it for me.
