### ISSUE TITLE
Callback when file is fully uploaded?

### ISSUE THREAD

**Issue by webrails** [mysecureshell/mysecureshell#50]
Hello,

is there a configuration option available that makes it possible to register a kind of callback script to be run whenever an upload is fully completed?

To give you a background for what I'm trying to achieve: Uploaded files should be processed right after the upload is completed. To observe the upload directory I'm currently using the Ruby lib https://github.com/guard/listen.

I can register a listener to events "added", "modified" and "removed". This works well for small files. It does however fire multiple times for bigger files: First right after beginning the upload and second when the upload is complete.

To make a long story short: I want to avoid implementing a logic checking if an upload is really complete. The easiest way I can imagine would be to register a callback script in the mysecureshell config. That callback should be fired only when an upload is complete.

Is there any way to do this?

Judging from the log files I'd say that mysecureshell does at least know the event when an upload is complete, as you can see in this example with a large video file:

```
2017-01-20 08:42:21 [30673][desk_38ba27e436][][18136]Start upload into file '/Bi_itsinTV.mp4'
2017-01-20 08:43:06 [30673][desk_38ba27e436][][18136]End upload into file '/Bi_itsinTV.mp4' (101707072 bytes)
```

Best regards
Marc

**Comment by Teka101** [comment]
Hi,

At this time, there is no way to have a handler/callback when an upload is finished.
But you can use log file (with grep on "End upload") to have the informations

**Comment by teunis90** [comment]
I'm also interested in this feature. We would like to avoid that feature versions have log changes and that we have to alter the logic on our side.

I would like to get in touch to sponsor this feature. Please contact me on teun@nextpertise.nl.

**Comment by Teka101** [comment]
Feature merged
