### ISSUE TITLE
Logging permission changes in /var/log/sftp-server.log 

### ISSUE THREAD

**Issue by ladowny** [mysecureshell/mysecureshell#53]
Hi 
Is it possible that changing permissions of the file/folder is logged ? 
It does log file uploads, downloads, deletes etc, but when I do chmod it does not get logged. Was looking through the docs but did not find any setting for it. Would be useful to see the permissions files were created with and if someone actually changed the permission on a file or folder. 

Thanks 

Greg

**Comment by Teka101** [comment]
Hi,

You can't configure logging when an user change permision of file/folder ...
