### ISSUE TITLE
SFTP users are jumping to other users home directory on first time login

### ISSUE THREAD

**Issue by spsunipoonia** [mysecureshell/mysecureshell#60]
Hi all,
All SFTP users are facing issue of accessing other sftp users home directory and when they are logging of and logging again they are able access their home directory correctly. I am facing this issue more than 3 months and users are getting very frustrated. This is happening intermittently every 3-4 days. 
We are using my secure shell version 1.31
Regards,
Sunil

**Comment by Teka101** [comment]
Hi,

Please use last version of MySecureShell 2.0 ;)
