### ISSUE TITLE
can see all the files and directories on the server

### ISSUE THREAD

**Issue by livix07** [mysecureshell/mysecureshell#62]
I had to use "**Subsystem sftp internal-sftp**" because of errors when uploading or downloading files. Now I can see and navigate to all files and folders on the server. It seems that the instructions in the **sftp_config** file don't work. It is the original **sftp_config** file.
How can I hide the file system on the server and restrict the user to the home folder?

**Comment by Teka101** [comment]
Hi,

Please read the documentations at http://mysecureshell.readthedocs.io/en/latest/ ;)

**Comment by livix07** [comment]
Thank you but can you direct me to the exact section of the documentation which explains why I can see all the files and folders when both **VirtualChroot** and **StayAtHome** are enabled in the **sftp_config** file and how to solve this problem?

**Comment by Teka101** [comment]
Hi,

Your configuration of SSHD (Subsystem should not be internal) is invalid, so MySecureShell can take control of SFTP :(

You can fix it with this : http://mysecureshell.readthedocs.io/en/latest/faq.html#only-allow-mysecureshell-users-for-sftp-connections

**Comment by livix07** [comment]
Thank you again.
As mentioned in my first message, I use **Subsystem sftp internal-sftp** because there errors when I try to upload or download files with **FileZilla**.  The error message is:
`Received unexpected end-of-file from SFTP server`

**Comment by Teka101** [comment]
FileZilla needs 2 connections by user in order to work.

Can you paste your configuration of MSS ?

**Comment by livix07** [comment]
Please see attachment.
Isn't **FileZilla** supposed to use **port 22** only with **sftp
[sftp_config.txt](https://github.com/mysecureshell/mysecureshell/files/1755869/sftp_config.txt)
** protocol?

**Comment by Teka101** [comment]
FileZilla  use port 22 for sftp (sftp is not ftps), but he need 2 connections (bad sftp client)...

Please change LimitConnectionByUser & LimitConnectionByIP to 2 :)

**Comment by livix07** [comment]
Nope, it does NOT. It only works with **Subsystem sftp internal-sftp**.

**Comment by Teka101** [comment]
With VirtualChroot and an symlink in their folders.

**Comment by livix07** [comment]
Do you mean I should do **VirtualChroot false** and create a symlink inside the user's folder?

**Comment by livix07** [comment]
Thank you. It works now.
In my case works even with **VirtualChroot true** and **StayAtHome true**

**Comment by Teka101** [comment]
:+1:
