### ISSUE TITLE
allow sftp access, forbid ssh connection but leave access to the shell with the command "su [user]"

### ISSUE THREAD

**Issue by MrZyr0** [mysecureshell/mysecureshell#64]
Hello,

All is in the title...
I setup a debian VPS to run a minecraft server. And I want to have a user named 'minecraft' who can access to the files of the server via sftp. To do this I use openssh and mysecureshell to chroot and secure the access.

But to further secure the ssh I want to have just my personnal account who can connect. And after connection use the su commande to access to the minecraft account.

I search many times but when i disable the ssh login, i can't connect on sftp...
And when i set 'Shell /bin/nologin' I can access to SFTP but I can't use su command to connect on the user...

In fact i want to have somethings compared to 'adduser minecraft --disabled-login --disabled-password'

There is a function to do this ? 
Or can we create this ?

Thanks

**Comment by Teka101** [comment]
Hi,

Use "su --shell /bin/bash minecraft" ;)

**Comment by MrZyr0** [comment]
: O God it's work !!! So good !!

And just to be sure, when I use this command, I give a temporary shell no?

Do my programs continue to run after a disconnect?
For example :
I log in with minecraft and launch a sh file to launch the java server.
I disconnect from the user minecraft and my personal account to close my ssh connection. The minecraft server will still work?

**Comment by Teka101** [comment]
Using "--shell" in "su" override shell of an user (so it's only work for this command).

Yes, if you are using some tool like "nohup"

**Comment by MrZyr0** [comment]
It's override just in moment, until I disconnect the user ? is it correct ?

What is "nohup" ?

**Comment by Teka101** [comment]
Yes just for the command until you disconnect the user

"nohup" is generally used when you put a command line in background

**Comment by MrZyr0** [comment]
ok thank you.

I still have one more problem in another subject.

I have 2 user : minecraft and julien.

I want to have full access (rwx) of minecraft home with julien account

I have try to change permissions with chmod and chown but it doesn't work...
currently minecraft can have access correctly to his folders but julien see an empty folder ! whereas  there is stuff in it....

**Comment by Teka101** [comment]
Here the default config of MySecureShell : https://github.com/mysecureshell/mysecureshell/blob/master/sftp_config

Maybe you can add minecraft group to julien ;)

**Comment by MrZyr0** [comment]
Thanks, I'll keep this because I always forgot to do some backup ...

Yes ok I have thought about that

Thank you

**Comment by Teka101** [comment]
👍
