### ISSUE TITLE
Ability to disable file move

### ISSUE THREAD

**Issue by azfarhashmi** [mysecureshell/mysecureshell#66]
I want to disable users to move any file from one directory to another, write now I am using DisableRemoveDir and DisableRemoveFile to stop users to accidentally delete files but they can still accidentally drag and drop files an folders.   

EEDIT:

Looks like I missed the DisableRename directive in my testing.

**Comment by Teka101** [comment]
Hello @azfarhashmi,

So I can close the ticket ? :)

**Comment by azfarhashmi** [comment]
sure.
