### ISSUE TITLE
Some Directives not working

### ISSUE THREAD

**Issue by azfarhashmi** [mysecureshell/mysecureshell#67]
Some directives are not working for me such as ForceUser, ForceGroup and LogFile atleast.

My config is below.

`<User sftp>`
`Home /home/sftp`
`ForceUser myuser`
`ForceGroup mygroup`
`DisableRemoveDir true`
`DisableRemoveFile true`
`DisableRename true`
`StayAtHome true`
`Shell /bin/bash`
`LogFile /var/log/sftp.log`
`</User>`

All other directives are working such as disableremovedir/file/rename etc but all new files and folders are always being created under "sftp" user and custom log file is also not creating.

Debian > 8.10
Mysecureshell > 2.0-1

**Comment by Teka101** [comment]
Please check your installation with the command `sftp-verif`

(see docs http://mysecureshell.readthedocs.io/en/latest/faq.html?highlight=verif#some-features-seem-not-working-correctly)

**Comment by azfarhashmi** [comment]
Thanks Teka,

It was a right issue.

**Comment by Teka101** [comment]
:+1:
