### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by Geartwo** [mysecureshell/mysecureshell#70]
I have the problem that I dont see the commands that are blocked by MSS. Is there any kind of Log Level setting to debug this failures?

**Comment by Teka101** [comment]
Hi,

There is no way to change log level, MySecureShell always show all informations

**Comment by Teka101** [comment]
When you use SCP, it open an another channel in SSH for a shell session, MySecureShell show it when it's disabled

**Comment by Teka101** [comment]
See MR #83
