### ISSUE TITLE
Home for root user

### ISSUE THREAD

**Issue by bazalt** [mysecureshell/mysecureshell#72]
Hello there,

I'm using MySecureShell for years and it's really great. Thank you for your work!

Just wondering if there's a way to define Home directive for root user? (I know, I know: this is a not a good idea to connect as root....)
Anyway, I put these following lines at the end of /etc/ssh/sftp_config:
```
<User root>
Home /srv/
</User>
```
Also tried to alter `Home` directive in `<Default>` section, but the result remains the same: while connecting with root user, I still get redirected to his $home directory: /root

I guess root user bypass MySecureShell?

**Comment by Teka101** [comment]
Hi,

User root has shell "/bin/mysecureshell"  ?

**Comment by bazalt** [comment]
Hi,
No, root remains with its default shell, as I would like to keep the possibility to connect with SSH.
Is there a workaround to conciliate both?

**Comment by Teka101** [comment]
Hi,

MySecureShell only work if user have "/bin/mysecureshell" as shell.
In order to keep SSH shell-access, you should use tag [Shell](https://mysecureshell.readthedocs.io/en/latest/tags/childs/shell.html).

**Comment by bazalt** [comment]
Thank you!
