### ISSUE TITLE
Using mysecureshell per key

### ISSUE THREAD

**Issue by Ulrar** [mysecureshell/mysecureshell#85]
Hey,

I've been trying to use mysecureshell for a specific key on a user, using `command="/usr/bin/mysecureshell" ssh-rsa ...` in the authorized_keys for that user, but I can't get it to work.
The same syntax with the regular sftp-server does work fine, is there somthing I should do to get mysecureshell to work ?

```
835 ~ % sftp user@server
Connection closed.  
Connection closed
```

The goal here is just to have a chrooted sftp for one of the keys only, letting other keys get a regular shell access.
Thanks

**Comment by Teka101** [comment]
Hi,

Please try with this line `command="/usr/bin/mysecureshell -c sftp-server" `
