### ISSUE TITLE
sftp-user create command does not accept home path (documentation error)

### ISSUE THREAD

**Issue by izenkov** [mysecureshell/mysecureshell#87]

**Comment by izenkov** [comment]
Hello,

I am in a process of moving from a default Open SSH SFTP server to MySecureShell, So I am mostly reading documentation at this point (https://mysecureshell.readthedocs.io/en/latest). It looks like https://mysecureshell.readthedocs.io/en/latest/usages_admin.html contains an error. It states: 
**> sftp-user create mssuser /home/mssuser** 
However **/home/mssuser** parameter is ignored by the sftp-user script.
In fact no user directory will be created on Linux/BSD because useradd will not create it by default.
The simplest solution is to update the documentation, better solution is to make sftp-user not to ignore home path directory ;-)

**Comment by Teka101** [comment]
Hello,

Ok, it's a little bug in the documentation ... there is no argument for home 👍 

Thanks

**Comment by izenkov** [comment]
Thank you Teka101

**Comment by Teka101** [comment]
👍
