### ISSUE TITLE
Buiding from source on Ubuntu 16.04 server: how-to enable File Hashing option?

### ISSUE THREAD

**Issue by izenkov** [mysecureshell/mysecureshell#90]
Hi,

I am trying to build mysecureshell from GitHub latest source master branch.
So far everything builds as expected however not all the options are getting compiled by default
For example in order to enable ACL option I had to install **libacl1-dev**

`$ sudo apt-get install libacl1-dev`

Question: what library do I need to install in order enable **File Hashing** option?

**Comment by Teka101** [comment]
Hi,

Just install package gnutls-dev and do `./configure`

**Comment by izenkov** [comment]
Thank you, Teka101!

After installing **gnutls-dev**:
`$ sudo apt-get install gnutls-dev`
'File Hashing' option in on now

**Comment by Teka101** [comment]
👍
