### ISSUE TITLE
Problem with ssh keys

### ISSUE THREAD

**Issue by bensz** [mysecureshell/mysecureshell#97]
Hello,
I have a user who use a key to login. He can connect correctly with /bin/bash in /etc/passwd. If I use mysecureshell with him, his connection wants the password. He has no password and I don't want to create one for him.
Mysecureshell is on a debian buster server up to date.
Thanks for ideas
Benoit

**Comment by Teka101** [comment]
Hello,

Take a look at this page: https://mysecureshell.readthedocs.io/en/latest/faq.html#how-can-i-make-a-passwordless-connection

You have to make a ssh key for your users.

**Comment by bensz** [comment]
Hello,

I add PubkeyAuthentication with yes parameter in sshd_config. I 
restartes sshd but nothing change. Is there a log where I can have 
information or do you have ideas?

I already have a ssh key for this user as it works with /bin/bash in 
/etc/passwd.

Thanks

Benoit

Le 26/03/2020 à 12:49, Teka101 a écrit :

**Comment by Teka101** [comment]
Hello,

If it work with bash then it should work with MySecureShell ...

**Comment by bensz** [comment]
I understand, but it doesn't.

extract from sftp_config:

<User presta>
         IsAdmin         false            #can admin the server
         VirtualChroot   false           #you must disable chroot to 
have a full support of admin
         StayAtHome      true
         IdleTimeOut     0
         Shell /bin/bash
</User>


extract from ssd_config


PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
AuthorizedKeysFile      .ssh/authorized_keys .ssh/authorized_keys2


Thanks for ideas

Benoit


Le 26/03/2020 à 14:34, Teka101 a écrit :

**Comment by Teka101** [comment]
Which sftp client is used ?

**Comment by bensz** [comment]
It's a rsync with ssh

Le 26/03/2020 à 14:54, Teka101 a écrit :

**Comment by Teka101** [comment]
Rsync is using ssh with shell access.
You cannot use rsync with MySecureShell features....

**Comment by bensz** [comment]
OK, I didn't know. Thank you for information. Is there another solution?

Thank you

Benoit


Le 26/03/2020 à 15:01, Teka101 a écrit :

**Comment by Teka101** [comment]
lftp support sftp and mirror functionnality

**Comment by bensz** [comment]
OK, Thank you

Benoit

Le 26/03/2020 à 15:22, Teka101 a écrit :
